
"""
生肖像素图 - 12x12 像素网格
每个生肖用字符画表示：
'.' = 透明
'B' = 主体色（调用时替换）
'D' = 深色（轮廓/细节）
'W' = 白色（眼睛/高光）
'R' = 红色（特殊细节）
'Y' = 黄色（特殊细节）
"""

# 12x12 像素图案（每行 12 字符）
ZODIAC_PIXELS = {
    # 鼠：圆耳 + 鼻
    "鼠": [
        "....DDDD....",
        "...DBBBBD...",
        "...DBBBBD...",
        "..DBBBBBBD..",
        "..DBBWBBBD..",
        "..DBBWBBBD..",
        "..DBBBBBD...",
        "..DBBBBBBD..",
        "...DBBBBD...",
        "....DDDD....",
        "............",
        "..DDDDDDDD..",
    ],
    "牛": [
        "D..........D",
        "DD........DD",
        ".DB......BD.",
        ".DBBBBBBBBD.",
        "..BBWBBBWBB.",
        "..BBBBBBBB..",
        "...BBBBBB...",
        "..BBBBBBBB..",
        ".BBBBBBBBBB.",
        "..BBBBBBBB..",
        "...DDDDDD...",
        "...DD..DD...",
    ],
    "虎": [
        "...DDDDDD...",
        "..DBBBBBBD..",
        "..DBBWBBBD..",
        "..DBBWYBBD..",
        "..DBBBBBBD..",
        "..DBBBBBBD..",
        "...BBBBBB...",
        "..BBBBBBBB..",
        ".BWBBBBBBWB.",
        "..BBBBBBBB..",
        "...BBBBBB...",
        "..DD....DD..",
    ],
    "兔": [
        ".D......D...",
        ".DD....DD...",
        ".DBD..DBD...",
        "..BBBBBBBB..",
        "..BBWBBWBB..",
        "..BBBBBBBB..",
        "...BBBBBB...",
        "..BBBBBBBB..",
        ".BBBBBBBBBB.",
        ".BBBBBBBBBB.",
        "..BBBBBBBB..",
        "...DDDDDD...",
    ],
    "龙": [
        "DD........DD",
        ".DD......DD.",
        "..BBBBBBBB..",
        "..DBWBBWBD..",
        "...DBBBBD...",
        "..DBBBBBBD..",
        ".DBBBBBBBBD.",
        "DBBBBBBBBBBD",
        "DBBBBBBBBBBD",
        ".DBBBBBBBBD.",
        "..DBBBBBBD..",
        "...D....D...",
    ],
    "蛇": [
        "............",
        "....DDDD....",
        "...DBBBBD...",
        "..DBBBBBBD..",
        ".DBBBBBBBBD.",
        "DBBBBBBBBBBD",
        "DBBBBBBBBBBD",
        ".DBBBBBBBBD.",
        "..DBBBBBBD..",
        "...DBBBBD...",
        "....DDDD....",
        "............",
    ],
    "马": [
        "...D....D...",
        "...DD..DD...",
        "...DB..BD...",
        "...DBBBBD...",
        "..DBBBBBBD..",
        "..BBWBBWBB..",
        "..BBBBBBBB..",
        "..BBBBBBBB..",
        ".BBBBBBBBBB.",
        ".BBBBBBBBBB.",
        "..BBBBBBBB..",
        "..DDD..DDD..",
    ],
    "羊": [
        "D...........",
        "DD.........D",
        ".DD.......DD",
        "..BBBBBBBBBB",
        "..BBWBBBBWBB",
        "..BBBBBBBBBB",
        "...BBBBBBBB.",
        "..BBBBBBBBBB",
        ".BBBBBBBBBBB",
        ".BBBBBBBBBBB",
        "..BBBBBBBBBB",
        "..DDDDDDDDDD",
    ],
    "猴": [
        ".D........D.",
        ".DD......DD.",
        "..DB....BD..",
        "..BBBBBBBB..",
        "..BWBBBBWB..",
        "..BBBBBBBB..",
        "...BBBBBB...",
        "..BBBBBBBB..",
        ".BBBBBBBBBB.",
        ".BBBBBBBBBB.",
        "..BBBBBBBB..",
        "...D....D...",
    ],
    "鸡": [
        "....R.......",
        "....R.......",
        "....RRR.....",
        "...BBBBBB...",
        "..BBBBBBBB..",
        "..BBWBBWBB..",
        "..BBBBBBBB..",
        "...BBBBBB...",
        "..BBBBBBBB..",
        "..BBBBBBYB..",
        "...DDDDDD...",
        "...DD..DD...",
    ],
    "狗": [
        "DD........DD",
        ".DD......DD.",
        "..BBBBBBBB..",
        "..BBWBBWBB..",
        "..BBBBBBBB..",
        "...BBBBBB...",
        "..BBBBBBBB..",
        ".BBBBBBBBBB.",
        ".BBBBBBBBBB.",
        ".BBBBBBBBBB.",
        "..BBBBBBBB..",
        "..DDD..DDD..",
    ],
    "猪": [
        "...DDDDDD...",
        "..DBBBBBBD..",
        "..DBWBBWBD..",
        "..DBBBBBBD..",
        "..DBBBBBBD..",
        "...BBBBBB...",
        "..BBBBBBBB..",
        "..BBBBBBBB..",
        "...BBBBBB...",
        "....BBBB....",
        "....BBBB....",
        "...DD..DD...",
    ],
}

# 颜色映射（每格字母 → 实际 RGB）
ZODIAC_COLORS = {
    "鼠": {"B": (150, 150, 150), "D": (80, 80, 80)},
    "牛": {"B": (139, 119, 80), "D": (90, 75, 50)},
    "虎": {"B": (220, 160, 40), "D": (140, 100, 30), "Y": (255, 200, 80)},
    "兔": {"B": (240, 220, 240), "D": (170, 150, 170)},
    "龙": {"B": (80, 200, 120), "D": (40, 120, 70)},
    "蛇": {"B": (100, 180, 80), "D": (50, 110, 45)},
    "马": {"B": (180, 130, 80), "D": (110, 80, 50)},
    "羊": {"B": (230, 230, 230), "D": (160, 160, 160)},
    "猴": {"B": (170, 120, 60), "D": (105, 70, 40)},
    "鸡": {"B": (220, 180, 60), "D": (140, 110, 40), "R": (220, 50, 50), "Y": (250, 220, 100)},
    "狗": {"B": (160, 120, 70), "D": (95, 70, 40)},
    "猪": {"B": (240, 180, 180), "D": (170, 120, 120)},
}
